# Generated by Django 4.2.5 on 2023-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
